### ISSUE TITLE
Getting a Fatal Error on Startup

### ISSUE THREAD

**Issue by Awosch28** [wishthis/docker#15]
I'm getting the following error after creating the containers:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/src/classes/wishthis/Database.php:38 Stack trace: #0 /var/www/html/src/classes/wishthis/Database.php(38): PDO->__construct('mysql:host=loca....', 'root', '', Array) #1 /var/www/html/index.php(76): wishthis\Database->connect() #2 {main} thrown in /var/www/html/src/classes/wishthis/Database.php on line 38`

Here is what is at `/var/www/html/src/classes/wishthis/Database.php`:
```
<?php

/**
 * database.php
 *
 * Establishes a database connection using its credentials.
 *
 * @author Jay Trees <github.jay@grandel.anonaddy.me>
 */

namespace wishthis;

class Database
{
    /**
     * Private
     */
    private int $lastInsertId;

    /**
     * Public
     */
    public \PDO $pdo;

    public function __construct(
        public string $host,
        public string $database,
        public string $user,
        public string $password,
    ) {
    }

    public function connect(): void
    {
        $dsn     = 'mysql:host=' . $this->host . ';dbname=' . $this->database . ';port=3306;charset=utf8mb4';
        $options = ['placeholders' => []];

        $this->pdo = new \PDO($dsn, $this->user, $this->password, $options);
    }

    public function query(string $query, array $placeholders = []): \PDOStatement|false
    {
        $statement = $this->pdo->prepare($query, [\PDO::FETCH_ASSOC]);

        foreach ($placeholders as $name => $value) {
            switch (gettype($value)) {
                case 'boolean':
                    $statement->bindValue($name, $value, \PDO::PARAM_BOOL);
                    break;

                case 'integer':
                    $statement->bindValue($name, $value, \PDO::PARAM_INT);
                    break;

                case 'NULL':
                    $statement->bindValue($name, $value, \PDO::PARAM_NULL);
                    break;

                default:
                    $statement->bindValue($name, $value, \PDO::PARAM_STR);
                    break;
            }
        }

        $statement->execute();

        $this->lastInsertId = $this->pdo->lastInsertId();

        return $statement;
    }

    public function lastInsertId(): int
    {
        return $this->lastInsertId;
    }

    public function tableExists(string $table_to_check): bool
    {
        $tables = $this
        ->query('SHOW TABLES;')
        ->fetchAll();

        if (!is_iterable($tables)) {
            return false;
        }

        foreach ($tables as $table_kv) {
            $table = reset($table_kv);

            if ($table === $table_to_check) {
                return true;
            }
        }

        return false;
    }

    public function columnExists(string $table_to_check, string $column_to_check): bool
    {
        $result = $this
        ->query(
            'SELECT *
               FROM `INFORMATION_SCHEMA`.`COLUMNS`
              WHERE `TABLE_NAME`  = :table_name
                AND `COLUMN_NAME` = :column_name',
            [
                'table_name'  => $table_to_check,
                'column_name' => $column_to_check,
            ]
        )
        ->fetch();
        $exists = false !== $result;

        return $exists;
    }
}
```

Here is what my docker-compose.yml look like:
```
version: '3.7'
services:
  wishthis:
    container_name: wishthis
    restart: unless-stopped
    image: hiob/wishthis:stable
    environment:
      - VIRTUAL_HOST=wishthis.domain.ext
    ports:
      - 80:80
    volumes:
      - ./config.php:/var/www/html/src/config/config.php
    networks:
      - wishthis
  mariadb:
    container_name: db
    restart: unless-stopped
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: wishthis
      MARIADB_USER: mariadb_user_1
      MARIADB_PASSWORD: test
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wishthis

networks:
  wishthis:
    external: true



```
I've also ensured that I've copied the sample config.php from the other repo.

**Comment by Awosch28** [comment]
In case it helps, here is what is at /var/www/html/index.php:

```
<?php

/**
 * wishthis - Make a wish
 *
 * @author Jay Trees <github.jay@grandel.anonaddy.me>
 */

namespace wishthis;

define('VERSION', '1.2.0');
define('ROOT', __DIR__);
define('DEFAULT_LOCALE', 'en_GB');

/**
 * Include
 */
require 'vendor/autoload.php';

$include = new \Grandel\IncludeDirectory(__DIR__ . '/src/functions');

spl_autoload_register(
    function (string $absoluteNamespace) {
        if (__NAMESPACE__ !== substr($absoluteNamespace, 0, strlen(__NAMESPACE__))) {
            return;
        }

        $absoluteNamespace = str_replace('\\', '/', $absoluteNamespace);

        $filepath = ROOT . '/src/classes/' . $absoluteNamespace . '.php';

        require $filepath;
    }
);

/**
 * Config
 */
$configPath = __DIR__ . '/' . 'src/config/config.php';
$config     = new Config($configPath);
$config->load();

/**
 * Session
 *
 * Has to be setup first, before anything else, so translations can be loaded.
 * The configuration is the only exception, since `loadFromSession` needs the
 * database.
 */
session_start(
    [
        'name' => 'wishthis',
    ]
);

$user = User::getCurrent();

/**
 * Database
 */
$database = false;
$options  = false;

if (
       defined('DATABASE_HOST')
    && defined('DATABASE_NAME')
    && defined('DATABASE_USER')
    && defined('DATABASE_PASSWORD')
) {
    $database = new Database(
        DATABASE_HOST,
        DATABASE_NAME,
        DATABASE_USER,
        DATABASE_PASSWORD
    );
    $database->connect();

    /**
     * Options
     */
    $options = new Options($database);

    /**
     * User session
     */
    $user->loadFromSession();
}

/**
 * Language
 */
\Locale::setDefault(DEFAULT_LOCALE);

/** Determine Locale */
$locales = array_filter(
    array_map(
        function ($value) {
            $extension = pathinfo($value, PATHINFO_EXTENSION);
            $filename  = pathinfo($value, PATHINFO_FILENAME);

            if ('po' === $extension) {
                return pathinfo($value, PATHINFO_FILENAME);
            }
        },
        scandir(ROOT . '/translations')
    )
);

$locale = isset($_REQUEST['locale']) ? $_REQUEST['locale'] : \Locale::lookup($locales, $user->getLocale(), false, 'en_GB');

/**
 * Wish
 */
Wish::initialize();

/**
 * Pretty URLs
 */
$url = new URL($_SERVER['REQUEST_URI']);

/**
 * Database Update
 */
if ($options && $options->getOption('isInstalled')) {
    if (-1 === version_compare($options->version, VERSION)) {
        $options->setOption('updateAvailable', true);
    }
}

/**
 * Page
 */
if (!isset($page)) {
    $page = isset($_GET['page']) ? $_GET['page'] : 'home';
}
$pagePath    = 'src/pages/' . $page . '.php';
$pagePathAlt = 'src/pages/' . $page . '/' . $page . '.php';

if (file_exists($pagePath)) {
    require $pagePath;
} elseif (\file_exists($pagePathAlt)) {
    require $pagePathAlt;
} else {
    http_response_code(404);
    ?>
    <h1>Not found</h1>
    <p>The requested URL was not found on this server.</p>
    <?php
    echo $pagePath;
    die();
}
```

**Comment by grandeljay** [comment]
Hello @Awosch28,

the image was created by @Hiobi, maybe he has an idea what's wrong here. Looking at the error:
```
SQLSTATE[HY000] [2002] Connection refused [...] PDO->__construct('mysql:host=loca....', 'root', '', Array) 
```
I'm guessing your database credentials are wrong.

Have you verified them?

**Comment by Hiobi** [comment]
Hi @Awosch28,


the docker image wasn't up-to-date ( note for myself : need to create automatic build with CI). 
I launched a new build, it works for me, on all branches, the container run correctly. 

Please make sure that your MySQL credentials are correct and check with the new build. Thanks ! 


Hey @grandeljay :3

**Comment by Hiobi** [comment]
I (think, I) reproduced the issue, I will check it ASAP @Awosch28

**Comment by Hiobi** [comment]
I obtain this issue, not clearly the same as you.
Could you retry and check your SQL credentials  and your network configuration in docker-compose.yml? 
Maybe you could share with us your docker network 'docker network inspect <network>'.



Here a sample for docker-compose.yml ( I use a predefine docker network, external)

```
services:
  wishthis:
    container_name: wishthis
    restart: unless-stopped
    image: ghcr.io/wishthis/docker:release-candidate
    environment:
     - VIRTUAL_HOST=wishthis.domain.com
    volumes:
     - ./config.php:/var/www/html/src/config/config.php
    networks:
      - wishthis-network

networks:
  wishthis-network:
    external: true
```

And config.php (maybe not up to date)

```
<?php

/**
 * config.php
 *
 * @author Jay Trees <github.jay@grandel.anonaddy.me>
 */

define('DATABASE_HOST', 'mariadb');
define('DATABASE_NAME', 'wishthis');
define('DATABASE_USER', 'awesomeuser');
define('DATABASE_PASSWORD', 'awesomepassword');

define('ENV_IS_DEV', false);

define(
    'CHANNELS',
    array(
        array(
            'branch' => 'stable',
            'host'   => 'wishthis.online',
        ),
        array(
            'branch' => 'release-candidate',
            'host'   => 'rc.wishthis.online',
        ),
    )
);
```

I will work on docker image to improvement it.


---

My issue  : 


```
Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session' at row 1 in /var/www/html/src/classes/wishthis/Database.php:65 Stack trace: #0 /var/www/html/src/classes/wishthis/Database.php(65): PDOStatement->execute() #1 /var/www/html/src/classes/wishthis/User.php(692): wishthis\Database->query('INSERT INTO `se...', Array) #2 /var/www/html/src/classes/wishthis/User.php(464): wishthis\User->refreshSession(1) #3 /var/www/html/src/pages/login.php(21): wishthis\User->logIn('mail@domain.com', 'password...', false) #4 /var/www/html/index.php(143): require('/var/www/html/s...') #5 {main} thrown in /var/www/html/src/classes/wishthis/Database.php on line 65
```

I can connect to my MySQL but the string seems to be too long for column "session", maybe @grandeljay can help on this.
